import { describe, it, expect, vi, beforeEach } from 'vitest';
import { compileMapping, deleteMapping, normalizeRepoUrl, buildEditLink } from '../compiler';
import { DepGraph } from '../graph';
import type { Mapping, Source } from '../types';
import type { FsOps } from '../fs/types';

// Mock logger to avoid console output during tests
vi.mock('../logger', () => ({
  logger: {
    info: vi.fn(),
    success: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  },
}));

describe('compileMapping', () => {
  let mockFs: FsOps;
  let graph: DepGraph;
  let mapping: Mapping;
  let sourcePaths: Record<string, string>;
  let sources: Record<string, Source>;

  beforeEach(() => {
    graph = new DepGraph();
    mapping = {
      from: 'common:source.md',
      to: 'docs/output.md',
    };

    sourcePaths = {
      common: '/cache/common',
      'other-source': '/cache/other-source',
    };

    sources = {
      common: { repo: 'https://github.com/org/common.git', branch: 'main' },
      'other-source': { repo: 'https://github.com/org/other.git', branch: 'main' },
    };

    mockFs = {
      exists: vi.fn(),
      readFileSync: vi.fn(),
      writeFileSync: vi.fn(),
      ensureDir: vi.fn(),
      stat: vi.fn(),
      unlinkSync: vi.fn(),
    };
  });

  it('should compile simple mapping', () => {
    const sourceContent = '# Hello World';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    expect(mockFs.readFileSync).toHaveBeenCalledWith('/cache/common/source.md');
    expect(mockFs.ensureDir).toHaveBeenCalledWith('docs');
    expect(mockFs.writeFileSync).toHaveBeenCalled();

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[0]).toBe('docs/output.md');
    expect(writeCall[1]).toContain('# Hello World');
    expect(writeCall[1]).toContain('GENERATED BY docs-sync');
  });

  it('should process includes', () => {
    const sourceContent = '<!-- @include common:snippet.md -->';
    const snippetContent = 'Snippet content';

    vi.mocked(mockFs.readFileSync)
      .mockReturnValueOnce(sourceContent)
      .mockReturnValueOnce(snippetContent);
    vi.mocked(mockFs.exists).mockReturnValue(true);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toContain('Snippet content');
    expect(writeCall[1]).not.toContain('@include');
  });

  it('should filter by site', () => {
    const sourceContent = `
# Header
<!-- @site site-a -->
Content for site-a
<!-- @endsite -->
<!-- @site site-b -->
Content for site-b
<!-- @endsite -->
`;

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toContain('Content for site-a');
    expect(writeCall[1]).not.toContain('Content for site-b');
  });

  it('should add dependencies to graph', () => {
    const sourceContent = '<!-- @include common:dep1.md -->\n<!-- @include common:dep2.md -->';

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);
    vi.mocked(mockFs.exists).mockReturnValue(false); // Files don't exist, will use error placeholder

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    // Should have recorded dependencies even though files don't exist
    const affected = graph.affected('common:dep1.md');
    expect(affected.has('common:source.md')).toBe(false); // deps are recorded but placeholder used
  });

  it('should include content hash in output', () => {
    const sourceContent = '# Test Content';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toMatch(/hash: [a-f0-9]+/);
  });

  it('should ensure target directory exists', () => {
    const sourceContent = '# Test';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    mapping.to = 'docs/nested/path/output.md';
    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    expect(mockFs.ensureDir).toHaveBeenCalledWith('docs/nested/path');
  });

  it('should throw error if source file read fails', () => {
    vi.mocked(mockFs.readFileSync).mockImplementation(() => {
      throw new Error('File not found');
    });

    expect(() => {
      compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);
    }).toThrow();
  });

  it('should handle complex compilation with includes and site filtering', () => {
    const sourceContent = `
# Main Content
<!-- @include common:intro.md -->
<!-- @site site-a -->
Site A specific content
<!-- @endsite -->
<!-- @site site-b -->
Site B specific content
<!-- @endsite -->
`;
    const introContent = 'Introduction text';

    vi.mocked(mockFs.readFileSync)
      .mockReturnValueOnce(sourceContent)
      .mockReturnValueOnce(introContent);
    vi.mocked(mockFs.exists).mockReturnValue(true);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    const output = writeCall[1] as string;

    expect(output).toContain('Main Content');
    expect(output).toContain('Introduction text');
    expect(output).toContain('Site A specific content');
    expect(output).not.toContain('Site B specific content');
    expect(output).toContain('GENERATED BY docs-sync');
    expect(output).toMatch(/hash:/);
  });

  it('should work with different source keys', () => {
    mapping.from = 'other-source:file.md';
    const sourceContent = '# Other Source';

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    expect(mockFs.readFileSync).toHaveBeenCalledWith('/cache/other-source/file.md');
  });

  it('should add source frontmatter when content has no frontmatter', () => {
    const sourceContent = '# Hello World';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).toMatch(/^---\nsource: https:\/\/github\.com\/org\/common\/edit\/main\/source\.md\n---\n/);
  });

  it('should inject source into existing frontmatter', () => {
    const sourceContent = '---\ntitle: My Doc\n---\n# Hello World';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).toMatch(/^---\nsource: https:\/\/github\.com\/org\/common\/edit\/main\/source\.md\ntitle: My Doc\n---\n/);
    expect(output).toContain('# Hello World');
  });

  it('should overwrite existing source field in frontmatter without duplicating', () => {
    const sourceContent = '---\ntitle: My Doc\nsource: old-value\n---\n# Hello World';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    const matches = output.match(/^source:/gm);
    expect(matches).toHaveLength(1);
    expect(output).toContain('source: https://github.com/org/common/edit/main/source.md');
    expect(output).not.toContain('old-value');
  });

  it('should not inject frontmatter for local path sources', () => {
    sources['common'] = { repo: '/local/path/to/repo' };
    const sourceContent = '# Local Doc';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).not.toMatch(/^---/);
    expect(output).toContain('GENERATED BY docs-sync');
  });

  it('should not inject frontmatter for _sidebar.md', () => {
    mapping.from = 'common:_sidebar.md';
    const sourceContent = '* [Home](/)';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).not.toMatch(/^---/);
    expect(output).toContain('GENERATED BY docs-sync');
    expect(output).toContain('* [Home](/)');
  });

  it('should not inject frontmatter for nested _sidebar.md', () => {
    mapping.from = 'common:guides/_sidebar.md';
    const sourceContent = '* [Guide](guide.md)';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).not.toMatch(/^---/);
  });

  it('should handle srcPath containing colons correctly', () => {
    mapping.from = 'common:path/with:colon/file.md';
    const sourceContent = '# Content';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    expect(mockFs.readFileSync).toHaveBeenCalledWith('/cache/common/path/with:colon/file.md');
    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    expect(output).toContain('path/with:colon/file.md');
  });

  it('should place frontmatter before the GENERATED comment', () => {
    const sourceContent = '# Content';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, sources, 'site-a', graph, mockFs);

    const output = vi.mocked(mockFs.writeFileSync).mock.calls[0][1] as string;
    const frontmatterEnd = output.indexOf('---\n', 4); // closing ---
    const commentStart = output.indexOf('<!-- GENERATED BY docs-sync');
    expect(frontmatterEnd).toBeLessThan(commentStart);
  });
});

describe('deleteMapping', () => {
  let mockFs: FsOps;
  let graph: DepGraph;
  let mapping: Mapping;

  beforeEach(() => {
    graph = new DepGraph();
    mapping = {
      from: 'common:source.md',
      to: 'docs/output.md',
    };

    mockFs = {
      exists: vi.fn(),
      readFileSync: vi.fn(),
      writeFileSync: vi.fn(),
      ensureDir: vi.fn(),
      stat: vi.fn(),
      unlinkSync: vi.fn(),
    };
  });

  it('should delete output file if it exists', () => {
    vi.mocked(mockFs.exists).mockReturnValue(true);

    deleteMapping(mapping, graph, mockFs);

    expect(mockFs.exists).toHaveBeenCalledWith('docs/output.md');
    expect(mockFs.unlinkSync).toHaveBeenCalledWith('docs/output.md');
  });

  it('should not attempt to delete if output file does not exist', () => {
    vi.mocked(mockFs.exists).mockReturnValue(false);

    deleteMapping(mapping, graph, mockFs);

    expect(mockFs.exists).toHaveBeenCalledWith('docs/output.md');
    expect(mockFs.unlinkSync).not.toHaveBeenCalled();
  });

  it('should remove mapping from dependency graph', () => {
    // Set up graph with dependencies
    graph.addDep('common:source.md', 'target1');
    graph.addDep('common:source.md', 'target2');

    vi.mocked(mockFs.exists).mockReturnValue(true);

    deleteMapping(mapping, graph, mockFs);

    // Verify the dependency was removed
    expect(graph.reverse.has('common:source.md')).toBe(false);
  });

  it('should remove mapping from graph even if file delete fails', () => {
    vi.mocked(mockFs.exists).mockReturnValue(true);
    vi.mocked(mockFs.unlinkSync).mockImplementation(() => {
      throw new Error('Permission denied');
    });

    // Set up graph
    graph.addDep('common:source.md', 'target1');

    expect(() => {
      deleteMapping(mapping, graph, mockFs);
    }).toThrow('Permission denied');

    // Graph should not be modified if operation fails
    expect(graph.reverse.has('common:source.md')).toBe(true);
  });

  it('should handle deletion when mapping has multiple dependencies', () => {
    // Build a graph where source.md is used by multiple targets
    graph.addDep('common:snippet.md', 'common:source.md');
    graph.addDep('common:source.md', 'target1');
    graph.addDep('common:source.md', 'target2');

    console.log('\n=== Before Deleting common:source.md (Multiple Dependencies) ===');
    console.log(graph.visualize());

    vi.mocked(mockFs.exists).mockReturnValue(true);

    deleteMapping(mapping, graph, mockFs);

    console.log('\n=== After Deleting common:source.md ===');
    console.log(graph.visualize());
    console.log('');

    // common:source.md should be removed from graph
    expect(graph.reverse.has('common:source.md')).toBe(false);

    // common:snippet.md should still exist, but common:source.md should be removed from its targets
    const snippetTargets = graph.reverse.get('common:snippet.md');
    expect(snippetTargets?.has('common:source.md')).toBe(false);
  });

  it('should work when mapping has no dependencies in graph', () => {
    vi.mocked(mockFs.exists).mockReturnValue(true);

    // No dependencies added to graph
    deleteMapping(mapping, graph, mockFs);

    expect(mockFs.unlinkSync).toHaveBeenCalledWith('docs/output.md');
    expect(graph.reverse.has('common:source.md')).toBe(false);
  });
});

describe('normalizeRepoUrl', () => {
  it('should strip .git from HTTPS URL', () => {
    expect(normalizeRepoUrl('https://github.com/org/repo.git')).toBe('https://github.com/org/repo');
  });

  it('should leave HTTPS URL without .git unchanged', () => {
    expect(normalizeRepoUrl('https://gitcode.com/dcloud/docs-common')).toBe('https://gitcode.com/dcloud/docs-common');
  });

  it('should convert ssh:// URL with port to HTTPS', () => {
    expect(normalizeRepoUrl('ssh://git@git.dcloud.io:2222/liuxiaohang/docs-common.git'))
      .toBe('https://git.dcloud.io/liuxiaohang/docs-common');
  });

  it('should convert ssh:// URL without port to HTTPS', () => {
    expect(normalizeRepoUrl('ssh://git@github.com/org/repo.git'))
      .toBe('https://github.com/org/repo');
  });

  it('should convert git@host:path shorthand to HTTPS', () => {
    expect(normalizeRepoUrl('git@github.com:org/repo.git'))
      .toBe('https://github.com/org/repo');
  });
});

describe('buildEditLink', () => {
  it('should build GitHub-style edit link', () => {
    expect(buildEditLink('https://github.com/org/repo.git', 'main', 'docs/guide.md'))
      .toBe('https://github.com/org/repo/edit/main/docs/guide.md');
  });

  it('should build GitCode edit link', () => {
    expect(buildEditLink('https://gitcode.com/dcloud/docs-common.git', 'main', 'ai/vibe-partner.md'))
      .toBe('https://gitcode.com/dcloud/docs-common/edit/main/ai/vibe-partner.md');
  });

  it('should build Gitee edit link', () => {
    expect(buildEditLink('https://gitee.com/org/repo.git', 'master', 'README.md'))
      .toBe('https://gitee.com/org/repo/edit/master/README.md');
  });

  it('should build edit link from SSH URL with port (gitcode scenario)', () => {
    expect(buildEditLink('ssh://git@git.dcloud.io:2222/liuxiaohang/docs-common.git', 'main', 'guides/install.md'))
      .toBe('https://git.dcloud.io/liuxiaohang/docs-common/edit/main/guides/install.md');
  });

  it('should build GitLab /-/edit link', () => {
    expect(buildEditLink('https://gitlab.com/org/repo.git', 'main', 'src/file.md'))
      .toBe('https://gitlab.com/org/repo/-/edit/main/src/file.md');
  });

  it('should build Bitbucket edit link', () => {
    expect(buildEditLink('https://bitbucket.org/org/repo.git', 'main', 'docs/file.md'))
      .toBe('https://bitbucket.org/org/repo/src/main/docs/file.md?mode=edit&spa=0&at=main&fileviewer=file-view-default');
  });
});
