import { describe, it, expect, vi, beforeEach } from 'vitest';
import { compileMapping } from '../compiler';
import { DepGraph } from '../graph';
import type { Mapping } from '../types';
import type { FsOps } from '../fs/types';

// Mock logger to avoid console output during tests
vi.mock('../logger', () => ({
  logger: {
    info: vi.fn(),
    success: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  },
}));

describe('compileMapping', () => {
  let mockFs: FsOps;
  let graph: DepGraph;
  let mapping: Mapping;
  let sourcePaths: Record<string, string>;

  beforeEach(() => {
    graph = new DepGraph();
    mapping = {
      from: 'common:source.md',
      to: 'docs/output.md',
    };

    sourcePaths = {
      common: '/cache/common',
      'other-source': '/cache/other-source',
    };

    mockFs = {
      exists: vi.fn(),
      readFileSync: vi.fn(),
      writeFileSync: vi.fn(),
      ensureDir: vi.fn(),
      stat: vi.fn(),
    };
  });

  it('should compile simple mapping', () => {
    const sourceContent = '# Hello World';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    expect(mockFs.readFileSync).toHaveBeenCalledWith('/cache/common/source.md');
    expect(mockFs.ensureDir).toHaveBeenCalledWith('docs');
    expect(mockFs.writeFileSync).toHaveBeenCalled();

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[0]).toBe('docs/output.md');
    expect(writeCall[1]).toContain('# Hello World');
    expect(writeCall[1]).toContain('GENERATED BY docs-sync');
  });

  it('should process includes', () => {
    const sourceContent = '<!-- @include common:snippet.md -->';
    const snippetContent = 'Snippet content';

    vi.mocked(mockFs.readFileSync)
      .mockReturnValueOnce(sourceContent)
      .mockReturnValueOnce(snippetContent);
    vi.mocked(mockFs.exists).mockReturnValue(true);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toContain('Snippet content');
    expect(writeCall[1]).not.toContain('@include');
  });

  it('should filter by site', () => {
    const sourceContent = `
# Header
<!-- @site site-a -->
Content for site-a
<!-- @endsite -->
<!-- @site site-b -->
Content for site-b
<!-- @endsite -->
`;

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toContain('Content for site-a');
    expect(writeCall[1]).not.toContain('Content for site-b');
  });

  it('should add dependencies to graph', () => {
    const sourceContent = '<!-- @include common:dep1.md -->\n<!-- @include common:dep2.md -->';

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);
    vi.mocked(mockFs.exists).mockReturnValue(false); // Files don't exist, will use error placeholder

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    // Should have recorded dependencies even though files don't exist
    const affected = graph.affected('common:dep1.md');
    expect(affected.has('common:source.md')).toBe(false); // deps are recorded but placeholder used
  });

  it('should include content hash in output', () => {
    const sourceContent = '# Test Content';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    expect(writeCall[1]).toMatch(/hash: [a-f0-9]+/);
  });

  it('should ensure target directory exists', () => {
    const sourceContent = '# Test';
    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    mapping.to = 'docs/nested/path/output.md';
    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    expect(mockFs.ensureDir).toHaveBeenCalledWith('docs/nested/path');
  });

  it('should throw error if source file read fails', () => {
    vi.mocked(mockFs.readFileSync).mockImplementation(() => {
      throw new Error('File not found');
    });

    expect(() => {
      compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);
    }).toThrow();
  });

  it('should handle complex compilation with includes and site filtering', () => {
    const sourceContent = `
# Main Content
<!-- @include common:intro.md -->
<!-- @site site-a -->
Site A specific content
<!-- @endsite -->
<!-- @site site-b -->
Site B specific content
<!-- @endsite -->
`;
    const introContent = 'Introduction text';

    vi.mocked(mockFs.readFileSync)
      .mockReturnValueOnce(sourceContent)
      .mockReturnValueOnce(introContent);
    vi.mocked(mockFs.exists).mockReturnValue(true);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    const writeCall = vi.mocked(mockFs.writeFileSync).mock.calls[0];
    const output = writeCall[1] as string;

    expect(output).toContain('Main Content');
    expect(output).toContain('Introduction text');
    expect(output).toContain('Site A specific content');
    expect(output).not.toContain('Site B specific content');
    expect(output).toContain('GENERATED BY docs-sync');
    expect(output).toMatch(/hash:/);
  });

  it('should work with different source keys', () => {
    mapping.from = 'other-source:file.md';
    const sourceContent = '# Other Source';

    vi.mocked(mockFs.readFileSync).mockReturnValue(sourceContent);

    compileMapping(mapping, sourcePaths, 'site-a', graph, mockFs);

    expect(mockFs.readFileSync).toHaveBeenCalledWith('/cache/other-source/file.md');
  });
});
