import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import { syncAll } from '../engine';
import { realFs } from '../fs/realFs';
import type { DocsSyncConfig } from '../types';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

// Mock logger for cleaner test output
vi.mock('../logger', () => ({
  logger: {
    info: vi.fn(),
    success: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn(),
  },
}));

describe('Integration Tests', () => {
  const testDir = path.join(process.cwd(), '.test-integration');
  const cacheDir = path.join(testDir, '.cache');
  const outputDir = path.join(testDir, 'output');

  beforeEach(() => {
    // Clean up and create test directories
    if (fs.existsSync(testDir)) {
      fs.rmSync(testDir, { recursive: true });
    }
    fs.mkdirSync(testDir, { recursive: true });
    fs.mkdirSync(cacheDir, { recursive: true });
    fs.mkdirSync(outputDir, { recursive: true });
  });

  afterEach(() => {
    // Clean up
    if (fs.existsSync(testDir)) {
      fs.rmSync(testDir, { recursive: true });
    }
  });

  it.skip('should complete full sync workflow', async () => {
    // Create a fake git repository
    const repoDir = path.join(cacheDir, 'common');
    fs.mkdirSync(repoDir, { recursive: true });

    // Initialize git repo
    execSync('git init', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.email "test@test.com"', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.name "Test User"', { cwd: repoDir, stdio: 'pipe' });

    // Create source files
    const sourceFile = path.join(repoDir, 'guide.md');
    const snippetFile = path.join(repoDir, 'snippets', 'note.md');

    fs.mkdirSync(path.dirname(snippetFile), { recursive: true });

    fs.writeFileSync(sourceFile, `# Installation Guide

<!-- @include common:snippets/note.md -->

<!-- @site site-a -->
## Site A Instructions
Install for Site A
<!-- @endsite -->

<!-- @site site-b -->
## Site B Instructions
Install for Site B
<!-- @endsite -->

## Common Steps
Follow these steps
`);

    fs.writeFileSync(snippetFile, `---
title: Note
---

> **Note**: This is an important note.`);

    // Commit files
    execSync('git add .', { cwd: repoDir, stdio: 'pipe' });
    execSync('git commit -m "Initial commit"', { cwd: repoDir, stdio: 'pipe' });

    // Create config
    const config: DocsSyncConfig = {
      site: 'site-a',
      cacheDir,
      sources: {
        common: {
          repo: repoDir,
          branch: 'master',
        },
      },
      mappings: [
        {
          from: 'common:guide.md',
          to: path.join(outputDir, 'guide.md'),
        },
      ],
    };

    // Run sync
    await syncAll(config);

    // Verify output
    const outputFile = path.join(outputDir, 'guide.md');
    expect(fs.existsSync(outputFile)).toBe(true);

    const output = fs.readFileSync(outputFile, 'utf-8');

    // Should contain header comment
    expect(output).toContain('GENERATED BY docs-sync');
    expect(output).toMatch(/hash: [a-f0-9]+/);

    // Should contain main content
    expect(output).toContain('# Installation Guide');
    expect(output).toContain('Follow these steps');

    // Should include snippet (without frontmatter)
    expect(output).toContain('**Note**: This is an important note');
    expect(output).not.toContain('title: Note');

    // Should include site-a content only
    expect(output).toContain('Site A Instructions');
    expect(output).toContain('Install for Site A');
    expect(output).not.toContain('Site B Instructions');
    expect(output).not.toContain('Install for Site B');
  });

  it.skip('should handle multiple mappings', async () => {
    const repoDir = path.join(cacheDir, 'docs');
    fs.mkdirSync(repoDir, { recursive: true });

    execSync('git init', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.email "test@test.com"', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.name "Test User"', { cwd: repoDir, stdio: 'pipe' });

    // Create multiple source files
    fs.writeFileSync(path.join(repoDir, 'intro.md'), '# Introduction');
    fs.writeFileSync(path.join(repoDir, 'guide.md'), '# Guide');

    execSync('git add .', { cwd: repoDir, stdio: 'pipe' });
    execSync('git commit -m "Add docs"', { cwd: repoDir, stdio: 'pipe' });

    const config: DocsSyncConfig = {
      site: 'default',
      cacheDir,
      sources: {
        docs: {
          repo: repoDir,
          branch: 'master',
        },
      },
      mappings: [
        { from: 'docs:intro.md', to: path.join(outputDir, 'intro.md') },
        { from: 'docs:guide.md', to: path.join(outputDir, 'guide.md') },
      ],
    };

    await syncAll(config);

    expect(fs.existsSync(path.join(outputDir, 'intro.md'))).toBe(true);
    expect(fs.existsSync(path.join(outputDir, 'guide.md'))).toBe(true);

    const intro = fs.readFileSync(path.join(outputDir, 'intro.md'), 'utf-8');
    const guide = fs.readFileSync(path.join(outputDir, 'guide.md'), 'utf-8');

    expect(intro).toContain('# Introduction');
    expect(guide).toContain('# Guide');
  });

  it.skip('should track dependencies correctly', async () => {
    const repoDir = path.join(cacheDir, 'common');
    fs.mkdirSync(repoDir, { recursive: true });

    execSync('git init', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.email "test@test.com"', { cwd: repoDir, stdio: 'pipe' });
    execSync('git config user.name "Test User"', { cwd: repoDir, stdio: 'pipe' });

    const snippetDir = path.join(repoDir, 'snippets');
    fs.mkdirSync(snippetDir, { recursive: true });

    fs.writeFileSync(
      path.join(repoDir, 'doc.md'),
      '# Doc\n<!-- @include common:snippets/a.md -->\n<!-- @include common:snippets/b.md -->'
    );
    fs.writeFileSync(path.join(snippetDir, 'a.md'), 'Snippet A');
    fs.writeFileSync(path.join(snippetDir, 'b.md'), 'Snippet B');

    execSync('git add .', { cwd: repoDir, stdio: 'pipe' });
    execSync('git commit -m "Add files"', { cwd: repoDir, stdio: 'pipe' });

    const config: DocsSyncConfig = {
      site: 'default',
      cacheDir,
      sources: {
        common: {
          repo: repoDir,
          branch: 'master',
        },
      },
      mappings: [
        { from: 'common:doc.md', to: path.join(outputDir, 'doc.md') },
      ],
    };

    const graph = await syncAll(config);

    // Verify dependencies were tracked
    const affectedByA = graph.affected('common:snippets/a.md');
    const affectedByB = graph.affected('common:snippets/b.md');

    expect(affectedByA.has('common:doc.md')).toBe(true);
    expect(affectedByB.has('common:doc.md')).toBe(true);
  });
});
